# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/sunxfancy"
  mail: "mailto:sunxfancy@gmail.com"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/sun-xiao-fan-3"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/sxf.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: sunxfancy
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  vvliebe的博客: http://blog.vvliebe.com/


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 西风逍遥游，一只热爱生活的技术粉